version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pg_container_test_db_crud
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_container_test_db_crud
    ports:
      - "6379:6379"

volumes:
  pgdata: