spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: yC7f!kD$92gLr@3pZb#nWxUv
  expiration: 900000 # 15 min